### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by eserte** [tokuhirom/FormValidator-Lite#15] opened 2016-09-27 06:00 UTC
My smoker machines started to report failures while running the FormValidator-Lite-0.38 test suite:
```
Nonempty epilogue at /usr/perl5.24.0p/lib/site_perl/5.24.0/HTTP/Entity/Parser/MultiPart.pm line 153.
t/020_constraints/006_file-plack.t ............... 
Dubious, test returned 25 (wstat 6400, 0x1900)
No subtests run 
...
Nonempty epilogue at /usr/perl5.24.0p/lib/site_perl/5.24.0/HTTP/Entity/Parser/MultiPart.pm line 153.
# Looks like your test exited with 25 before it could output anything.
t/030_upload/004_plack.t ......................... 
Dubious, test returned 25 (wstat 6400, 0x1900)
Failed 3/3 subtests 
```

It seems that this happens with the recent Plack version (1.0041) (cannot give any statistical analysis about this, because Plack is not declared as an optional dependency).

**Comment by GeJ** [comment] 2016-09-28 06:45
The problem is indeed introduced since the latest version of Plack.
The good news is that I have a quick fix for this. The bad news is that I don't know if it is correct (RFC-wise). Anyway, here it is : 

- remove the trailing empty line in `t/dat/file_post.txt`
- decrease the size of the `CONTENT_LENGTH` value by one (the extra `\n` we just removed) in `t/020_constraints/006_file-plack.t` and `t/030_upload/004_plack.t`
and Voila! the tests pass.
Sadly, I don't know if the extra `\n` is required in the RFC or not, so I'm not sure if I should send a PR for this.
If anyone more knowledgeable than me can confirm I won't break anything I'll send a PR quickly.

**Comment by syohex** [comment] 2016-09-28 07:41
>            # RFC 2616 3.7.2 Multipart Types
>            # Unlike in RFC 2046, the epilogue of any multipart message MUST be
>            # empty; HTTP applications MUST NOT transmit the epilogue (even if the
>            # original multipart contains an epilogue). These restrictions exist in
>            # order to preserve the self-delimiting nature of a multipart message-
>            # body, wherein the "end" of the message-body is indicated by the
>            # ending multipart boundary.

`HTTP::MultiPartParser` which is used by Plack comments above thing.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html

**Comment by tokuhirom** [comment] 2016-09-28 08:06
I guess, \n was added by editor configration. please remove it.

**Closed** 2016-09-28 09:52 UTC
